### ISSUE TITLE
Repository is missing a license.

### ISSUE THREAD

**Issue by shueja-personal** [improv-wifi/sdk-js#18]
Hello,
I am an embedded software developer looking to implement the Improv protocol for Raspberry Pi.
I would like to use this JS SDK, but it does not have a license, so the code is actually “all rights reserved”, despite the intent of the project being free to implement. What license is intended for this JS SDK?

**Comment by balloob** [comment]
Oops! It's Apache 2.0 as mentioned in package.json.

Also please let us know when you have added it to the Pi! That's awesome.
